config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :subscriptions
  resources :tells
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#home"

  get 'publish/:id', :to => 'publisher#publish_tell'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :subscription
	belongs_to :tell
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user
	has_many :notifications, dependent: :delete_all

	enum subscription_type: [:title, :teller, :keyword]
end

app/models/tell.rb
class Tell < ApplicationRecord
	has_many :notifications, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
		if current_user
			@notifications = current_user.subscriptions.to_a.collect{|v| v.notifications.to_a }.flatten
		end
	end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def destroy
  	@notification = Notification.find(params[:id])
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Notification dismissed' }
      format.json { head :no_content }
    end
  end
end

app/controllers/publisher_controller.rb
class PublisherController < ApplicationController
  include Wisper::Publisher

  def publish_tell
  	@tell = Tell.find(params[:id])
    publish(:tell_publish, @tell)
    redirect_to @tell, notice: 'Tell was successfully published.'
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = current_user.subscriptions.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    tag_value = subscription_params["user_entry"]

    #If the tag_value is empty, we match everything, so build a notification for the entire Tell collection
    #Else search through Tell collection by subscription type, generating notifications for matching tags
    case subscription_params["subscription_type"]
      #Type = title
      when "0"
        @subscription = current_user.subscriptions.build({"title"=>tag_value, "subscription_type"=>0})

        tells = Tell.where(title: tag_value)
      #Type = teller
      when "1"
        @subscription = current_user.subscriptions.build({"teller"=>tag_value, "subscription_type"=>1})

        tells = Tell.where(tellerName: tag_value)
      #Type = keyword
      when "2"
        @subscription = current_user.subscriptions.build({"keyword"=>tag_value, "subscription_type"=>2})

        tells = Tell.where(keyword: tag_value)
      else
        puts "Something went wrong..."
    end

    if tag_value == ""
      tells = Tell.all
    end
    
    tells.each do |tell|
          @subscription.notifications.build({"tell_id"=>tell.id})
    end

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:user_entry, :subscription_type)
    end
end

app/controllers/tells_controller.rb
class TellsController < ApplicationController
  before_action :set_tell, only: [:show, :edit, :update, :destroy]

  # GET /tells
  # GET /tells.json
  def index
    @tells = Tell.all
  end

  # GET /tells/1
  # GET /tells/1.json
  def show
  end

  # GET /tells/new
  def new
    @tell = Tell.new
  end

  # GET /tells/1/edit
  def edit
  end

  # POST /tells
  # POST /tells.json
  def create
    @tell = Tell.new(tell_params)

    respond_to do |format|
      if @tell.save
        format.html { redirect_to controller: 'publisher', action: 'publish_tell', id: @tell.id }
      else
        format.html { render :new }
        format.json { render json: @tell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tells/1
  # PATCH/PUT /tells/1.json
  def update
    respond_to do |format|
      if @tell.update(tell_params)
        format.html { redirect_to @tell, notice: 'Tell was successfully updated.' }
        format.json { render :show, status: :ok, location: @tell }
      else
        format.html { render :edit }
        format.json { render json: @tell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tells/1
  # DELETE /tells/1.json
  def destroy
    @tell.destroy
    respond_to do |format|
      format.html { redirect_to tells_url, notice: 'Tell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tell
      @tell = Tell.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tell_params
      params.require(:tell).permit(:title, :tellerName, :keyword)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/tells_helper.rb
module TellsHelper
end

app/views/home/home.html.erb
<div class="jumbotron">
		<% if user_signed_in? %>
		<div class="row">
			<div class="col-2">
				<h2>Home</h2>
				<p>Welcome, <%= current_user.email %></p>
			</div>
			<div class="col-1"></div>
	  
	  		<div class="col-9">
			  	<%= render 'notifications/notification_list', notifications: @notifications %>
			</div>
		</div>     
		<% else %>
			<h2>Welcome to the ISC Tell Library!</h2>
			<p>Click below to create an account or log in, and start making subscriptions today!</p>
		  	<%= link_to 'Login', new_user_session_path, :class => "btn btn-primary" %>  	
		<% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
          <% if notificationCount > 0 %>
            <span class="badge badge-pill badge-primary" style="float:right;margin-bottom:-10px;"><%= notificationCount %></span>
          <% end %>
        <a class="navbar-brand" href="/">Home</a>
      </div>
        <ul class="nav justify-content-center">
          <li class="nav-item">
            <a class="nav-link" href="/tells">Tell Library</a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="/subscriptions">My Subcriptions</a>
            </li>
          <% end %>
        </ul>
    <form class="form-inline">
      <% if user_signed_in? %>

        <%= link_to('Logout', destroy_user_session_path, method: :delete, :class => "btn btn-primary") %>        

      <% else %>

          <%= link_to 'Login', new_user_session_path, :class => "btn btn-primary" %>

      <% end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StorytellingPubSub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar", notificationCount: (current_user ?  current_user.subscriptions.to_a.collect{|v| v.notifications.to_a }.flatten.count : 0) %>
    <% if notice %>
        <p class="alert alert-success mb-0"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-primary mb-0"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/notifications/_notification_list.html.erb
<div class="container textjustify-center">
  <h2>Notifications</h2>
  <% if notifications.empty? %>
    <p>
      No new notifications
    </p>  
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Tell Title</th>
          <th>Tell Teller</th>
          <th>Tell Keyword</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% notifications.each do |notification| %>
          <tr>
            <td><%= notification.tell.title %></td>
            <td><%= notification.tell.tellerName %></td>
            <td><%= notification.tell.keyword %></td>
            <td><%= link_to 'View Tell', notification.tell, :class => "btn btn-secondary" %></td>
            <td><%= link_to 'Subscription', notification.subscription, :class => "btn btn-secondary" %></td>
            <td><%= link_to 'Dismiss', notification, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/subscriptions/_form.html.erb
<div class="jumbotron">
  <%= form_with(model: subscription, local: true) do |form| %>
    <% if subscription.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

        <ul>
          <% subscription.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label "Enter Title/Teller name or Keyword (leave blank to subscribe to all)" %>
      <%= form.text_field :user_entry, :class => "form-control" %>
    </div>

    <br/>

    <div class="field">
      <%= form.label :subscription_type %>
      <%= form.select :subscription_type, Subscription.subscription_types, {}, :class => "form-control" %>
    </div>

    <br/>

    <div class="actions">
      <%= form.submit "Subscribe", :class => "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/subscriptions/edit.html.erb
<div class="jumbotron">
	<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription, :class => "btn btn-primary" %> |
<%= link_to 'Back', subscriptions_path, :class => "btn btn-primary" %>
</div>

app/views/subscriptions/index.html.erb
<div class="jumbotron">
  <p id="notice"><%= notice %></p>

<h2><%= current_user.email %>'s Subscriptions</h2>

<br>

<table class="table">
  <thead>
    <tr>
      <th>Tag</th>
      <th>Subscription Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <% if subscription.title %>
          <td><%= subscription.title == "" ? "*ALL*" : subscription.title %></td>
        <% elsif subscription.teller %>
          <td><%= subscription.teller == "" ? "*ALL*" : subscription.teller %></td>
        <% elsif subscription.keyword %>
          <td><%= subscription.keyword == "" ? "*ALL*" : subscription.keyword %></td>
        <% else %>
        <% end %>
        <td><%= subscription.subscription_type %></td>
        <td><%= link_to 'Details', subscription, :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription), :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Unsubscribe', subscription, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path, :class => "btn btn-primary" %>
</div>

app/views/subscriptions/new.html.erb
<div class="jumbotron">
	<h1>New Subscription</h1>
	<p>Subscribe to recieve notifications about tells. You can subscribe by tell title, teller or a keyword.</p>
	<%= render 'form', subscription: @subscription %>

	<%= link_to 'Back', subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<div class="jumbotron">
	<h1>Subscription Details</h1>
	<p>
	  <strong>User:</strong>
	  <%= @subscription.user.email %>
	</p>

	<p>
	  <strong>Tag:</strong>
	  <% if @subscription.title %>
          <td><%= @subscription.title == "" ? "*ALL*" : @subscription.title %></td>
        <% elsif @subscription.teller %>
          <td><%= @subscription.teller == "" ? "*ALL*" : @subscription.teller %></td>
        <% elsif @subscription.keyword %>
          <td><%= @subscription.keyword == "" ? "*ALL*" : @subscription.keyword %></td>
        <% else %>
       <% end %>
	</p> 

	<p>
	  <strong>Subscription Type:</strong>
	  <%= @subscription.subscription_type %>
	</p>

	<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
	<%= link_to 'Back', subscriptions_path %>
</div>

app/views/tells/_form.html.erb
<div class="jumbotron">
  <%= form_with(model: tell, local: true) do |form| %>
  <% if tell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tell.errors.count, "error") %> prohibited this tell from being saved:</h2>

      <ul>
        <% tell.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :tellerName %>
    <%= form.text_field :tellerName, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :keyword %>
    <%= form.text_field :keyword, :class => "form-control" %>
  </div>

  <div class="actions form-group">
    <%= form.submit "Publish", :class => "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/tells/edit.html.erb
<div class="jumbotron">
	<h1>Editing Tell</h1>

<%= render 'form', tell: @tell %>

<%= link_to 'Show', @tell, :class => "btn btn-primary" %> |
<%= link_to 'Back', tells_path, :class => "btn btn-primary" %>
</div>

app/views/tells/index.html.erb
<div class="jumbotron">
  <p id="notice"><%= notice %></p>
  <h1>Tell Library</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Tellername</th>
      <th>Keyword</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tells.each do |tell| %>
      <tr>
        <td><%= tell.title %></td>
        <td><%= tell.tellerName %></td>
        <td><%= tell.keyword %></td>
        <td><%= link_to 'Details', tell, :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Edit', edit_tell_path(tell), :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Delete', tell, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary" %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tell', new_tell_path, :class => "btn btn-primary" %>
</div>

app/views/tells/new.html.erb
<div class="jumbotron">
	<h1>New Tell</h1>

	<%= render 'form', tell: @tell %>

	<%= link_to 'Back', tells_path %>
</div>

app/views/tells/show.html.erb
<div class="jumbotron text-center">
	<p>
  <strong>Title:</strong>
  <%= @tell.title %>
</p>

<p>
  <strong>Tellername:</strong>
  <%= @tell.tellerName %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @tell.keyword %>
</p>

<%= link_to 'Edit', edit_tell_path(@tell) %> |
<%= link_to 'Back', tells_path %>
</div>